version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0


executors:
  pythonpygame:
    docker:
      - image: feralbert90/pokepong1:latest  # Dockerfile que se necesita de dockerhub

jobs:
  job-tests:
    executor: pythonpygame
    steps:
      - checkout  # Para obtener el código del repositorio
      - run:
          name: Run tests
          command: | 
                    pytest Game/tests
      - run:
          name: Run linting
          command: | 
                    pylint  --exit-zero Game
      - run:
          name: Run code coverage
          command: |
                    coverage run -m pytest Game
                    coverage report -m 
      - store_test_results:
          path: Game/tests/test-results.xml
      - sonarcloud/scan

  job-vulnerability:
    executor: pythonpygame
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            apt-get update
            apt-get install -y nodejs npm
      - run:
          name: Install Snyk
          command: |
            npm install -g snyk
      - run:
         name: Analize with Snyc
         command: |
            export SNYK_TOKEN=$SNYK_TOKEN
            cd Game
            snyk_output=$(snyk code test)
            echo "$snyk_output"
            if echo "$snyk_output" | grep -q 'High severity vulnerabilities found'; then
              echo "Detected high severity vulnerabilities. Failing the build."
              exit 1
            else
              echo "No high severity vulnerabilities found."
            fi

  job-create-deploy-artifact:
    executor: pythonpygame
    steps:
      - checkout
      - run:
          name: Install zip
          command: |
            apt-get update && apt-get install -y zip
      - run:
          name: Create artifacts directory
          command: mkdir -p artifacts
      - run:
          name: Package artifact
          command: cd Game && zip -r ../artifacts/myapp.zip ./*
      - run:
          name: Set Git Identity
          command: |
            git config user.email "albertferal@gmail.com"
            git config user.name "albertferal"
      - run:
          name: Publish to GitHub
          command: |
            git remote set-url origin https://$GITHUB_TOKEN@github.com/albertferal/artifact-try.git
            git add artifacts/myapp.zip
            git commit -m "Agregar artefacto myapp.zip"
            git push origin mainn

    
workflows:
  workflow-testing:
    jobs:
      - job-tests:
          context: SonarCloud
      - job-vulnerability:
          requires:
            - job-tests
      - job-create-deploy-artifact:
          requires:
            - job-vulnerability
          filters:
            branches:
              only: main