apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pong-app
spec:
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: default
  source:
    repoURL: 'https://github.com/albertferal/pokepong'
    targetRevision: main 
    path: k8s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
